# VacationPy
---

## Starter Code to Import Libraries and Load the Weather and Coordinates Data

In [2]:
# Dependencies and Setup
import hvplot.pandas
import pandas as pd
import requests
import gmaps

# Import API key
from api_keys import geoapify_key

from pprint import pprint

gmaps.configure(api_key=geoapify_key)

In [4]:
# Load the CSV file created in Part 1 into a Pandas DataFrame
city_data_df = pd.read_csv("../WeatherPy/output_data/cities.csv")

# Display sample data
city_data_df.head()

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,0,ushuaia,-54.8000,-68.3000,13.81,44,40,4.12,AR,1667874945
1,1,anchorage,61.2181,-149.9003,0.56,65,100,5.66,US,1667875270
2,2,kapaa,22.0752,-159.3190,26.72,77,40,5.66,US,1667875224
3,3,souillac,-20.5167,57.5167,23.21,78,40,2.57,MU,1667875374
4,4,nikolskoye,59.7035,30.7861,3.94,92,100,4.41,RU,1667875272

---

### Step 1: Create a map that displays a point for every city in the `city_data_df` DataFrame. The size of the point should be the humidity in each city.

In [5]:
#%%capture --no-display

# Configure the map plot
# point_size = city_data_df["Humidity"]
# city = city_data_df["City"]

# city_data_df.hvplot.points("Lng","Lat",geo=True, alpha=0.2, scale=point_size, color=["r","b","k"],
#     xlim=(-180, 180), ylim=(-90, 90), tiles=True, legend="top")#, label=city)

figure_layout = {
    'width': '400px',
    'height': '300px',
    'border': '1px solid black',
    'padding': '1px',
    'margin': '0 auto 0 auto'
}
fig = gmaps.figure()

# Configure the map plot
city_info = city_data_df.values.tolist()

locations = city_data_df[["Lat","Lng"]].astype(float)

list_of_infoboxes = [f"Lng: {city[3]}\nLat: {city[2]}\nCity: {city[1]}\nHumidity: {city[5]}" for city in city_info]

city_layer = gmaps.symbol_layer(
    locations, fill_color="rgba(0, 150, 0, 0.4)",
    stroke_color="rgba(0, 0, 150, 0.4)", scale=2,
    hover_text=list_of_infoboxes)

# Display the map
fig.add_layer(city_layer)

fig

Figure(layout=FigureLayout(height='420px'))

### Step 2: Narrow down the `city_data_df` DataFrame to find your ideal weather condition

In [6]:
# Narrow down cities that fit criteria and drop any results with null values
city_data_ideal_df = city_data_df[(city_data_df["Max Temp"] < 27) & (city_data_df["Max Temp"] > 21)]

# Drop any rows with null values
city_data_ideal_df.dropna(inplace=True)

# # Display sample data
city_data_ideal_df.head()

/var/folders/cl/0lthhlt16qz55rsyjlr9g11c0000gn/T/ipykernel_78348/2012581335.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  city_data_ideal_df.dropna(inplace=True)

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
2,2,kapaa,22.0752,-159.3190,26.72,77,40,5.66,US,1667875224
3,3,souillac,-20.5167,57.5167,23.21,78,40,2.57,MU,1667875374
8,8,hilo,19.7297,-155.0900,26.85,79,100,3.09,US,1667875413
15,15,atuona,-9.8000,-139.0333,25.07,71,99,6.72,PF,1667875696
19,19,rikitea,-23.1203,-134.9692,23.23,92,100,7.16,PF,1667875680

### Step 3: Create a new DataFrame called `hotel_df`.

In [7]:
# Use the Pandas copy function to create DataFrame called hotel_df to store the city, country, coordinates, and humidity
hotel_df = city_data_ideal_df[["City","Country","Lat","Lng","Humidity"]].copy()

# Add an empty column, "Hotel Name," to the DataFrame so you can store the hotel found using the Geoapify API
hotel_df["Hotel Name"] = ""

# Display sample data
hotel_df.head()

        City Country      Lat       Lng  Humidity Hotel Name
2      kapaa      US  22.0752 -159.3190        77
3   souillac      MU -20.5167   57.5167        78
8       hilo      US  19.7297 -155.0900        79
15    atuona      PF  -9.8000 -139.0333        71
19   rikitea      PF -23.1203 -134.9692        92

### Step 4: For each city, use the Geoapify API to find the first hotel located within 10,000 metres of your coordinates.

In [9]:
# Set parameters to search for a hotel
radius = 10000
params = {
    "radius": radius,
    "type": "lodging",
    "minPriceLevel": 4, # Restrict data to most expensive hotels
    "key": geoapify_key
}

# Print a message to follow up the hotel search
print("Starting hotel search")

# Iterate through the hotel_df DataFrame
for index, row in hotel_df.iterrows():

    # get latitude, longitude from the DataFrame and add to params
    lat = row["Lat"]
    lng = row["Lng"]
    
    params["location"] = f"{lat}, {lng}"
    
    # Set base URL
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # Make and API request using the params dictionary
    hotel_r = requests.get(base_url, params).json()
    
    # Grab the first hotel from the results and store the name in the hotel_df DataFrame
    try:
        hotel_df.loc[index, "Hotel Name"] = hotel_r["results"][0]["name"]
    except (KeyError, IndexError):
        # If no hotel is found, set the hotel name as "No hotel found".
        hotel_df.loc[index, "Hotel Name"] = "No hotel found"
        
    # Log the search results
    print(f"{hotel_df.loc[index, 'City']} - nearest hotel: {hotel_df.loc[index, 'Hotel Name']}")

# Display sample data
hotel_df.head()

Starting hotel search
kapaa - nearest hotel: No hotel found
souillac - nearest hotel: No hotel found
hilo - nearest hotel: No hotel found
atuona - nearest hotel: No hotel found
rikitea - nearest hotel: No hotel found
san patricio - nearest hotel: No hotel found
grand gaube - nearest hotel: No hotel found
custodia - nearest hotel: No hotel found
sao filipe - nearest hotel: No hotel found
saint-philippe - nearest hotel: No hotel found
bengkulu - nearest hotel: No hotel found
acapulco - nearest hotel: No hotel found
kalmunai - nearest hotel: No hotel found
atar - nearest hotel: No hotel found
port-gentil - nearest hotel: No hotel found
soplaviento - nearest hotel: No hotel found
dwarka - nearest hotel: No hotel found
hengyang - nearest hotel: No hotel found
butaritari - nearest hotel: No hotel found
luanda - nearest hotel: No hotel found
bundaberg - nearest hotel: No hotel found
umm lajj - nearest hotel: No hotel found
puerto carreno - nearest hotel: No hotel found
touros - nearest hotel: No hotel found
arinos - nearest hotel: No hotel found
avarua - nearest hotel: No hotel found
emerald - nearest hotel: No hotel found
salalah - nearest hotel: No hotel found
airai - nearest hotel: No hotel found
bambous virieux - nearest hotel: No hotel found
victoria - nearest hotel: No hotel found
mangan - nearest hotel: No hotel found
jiquipilas - nearest hotel: No hotel found
carnarvon - nearest hotel: No hotel found
tigre - nearest hotel: No hotel found
mormugao - nearest hotel: No hotel found
tautira - nearest hotel: No hotel found
axim - nearest hotel: No hotel found
fomboni - nearest hotel: No hotel found
bay saint louis - nearest hotel: No hotel found
houma - nearest hotel: No hotel found
adrar - nearest hotel: No hotel found
zirandaro - nearest hotel: No hotel found
maragogi - nearest hotel: No hotel found
kayes - nearest hotel: No hotel found
caucasia - nearest hotel: No hotel found
bandarbeyla - nearest hotel: No hotel found
alofi - nearest hotel: No hotel found
karratha - nearest hotel: No hotel found
neuquen - nearest hotel: No hotel found
natal - nearest hotel: No hotel found
ormond beach - nearest hotel: No hotel found
vaitape - nearest hotel: No hotel found
flinders - nearest hotel: No hotel found
uong bi - nearest hotel: No hotel found
changde - nearest hotel: No hotel found
bharatpur - nearest hotel: No hotel found
pangkalanbuun - nearest hotel: No hotel found
geraldton - nearest hotel: No hotel found
rey bouba - nearest hotel: No hotel found
mahebourg - nearest hotel: No hotel found
ulladulla - nearest hotel: No hotel found
lascahobas - nearest hotel: No hotel found
mount gambier - nearest hotel: No hotel found
sinazongwe - nearest hotel: No hotel found
itaituba - nearest hotel: No hotel found
tevaitoa - nearest hotel: No hotel found
wonthaggi - nearest hotel: No hotel found
pedasi - nearest hotel: No hotel found
rio cuarto - nearest hotel: No hotel found
vao - nearest hotel: No hotel found
richards bay - nearest hotel: No hotel found
moundou - nearest hotel: No hotel found
gogrial - nearest hotel: No hotel found
dhidhdhoo - nearest hotel: No hotel found
araouane - nearest hotel: No hotel found
iquitos - nearest hotel: No hotel found
tianmen - nearest hotel: No hotel found
comodoro rivadavia - nearest hotel: No hotel found
berbera - nearest hotel: No hotel found
kawalu - nearest hotel: No hotel found
pochutla - nearest hotel: No hotel found
yeppoon - nearest hotel: No hotel found
lufkin - nearest hotel: No hotel found
saint-pierre - nearest hotel: No hotel found
xai-xai - nearest hotel: No hotel found
khanpur - nearest hotel: No hotel found
quatre cocos - nearest hotel: No hotel found
lagos - nearest hotel: No hotel found
palm coast - nearest hotel: No hotel found
puerto escondido - nearest hotel: No hotel found
terenos - nearest hotel: No hotel found
arauca - nearest hotel: No hotel found
sikasso - nearest hotel: No hotel found
itupiranga - nearest hotel: No hotel found
cayenne - nearest hotel: No hotel found
cap malheureux - nearest hotel: No hotel found
cockburn town - nearest hotel: No hotel found
carauari - nearest hotel: No hotel found
port lincoln - nearest hotel: No hotel found
maceio - nearest hotel: No hotel found
codrington - nearest hotel: No hotel found
moron - nearest hotel: No hotel found
puerto del rosario - nearest hotel: No hotel found
boende - nearest hotel: No hotel found
birao - nearest hotel: No hotel found
ibra - nearest hotel: No hotel found
batie - nearest hotel: No hotel found
cabo san lucas - nearest hotel: No hotel found
salinopolis - nearest hotel: No hotel found
baraya - nearest hotel: No hotel found
swan hill - nearest hotel: No hotel found
gboko - nearest hotel: No hotel found
sungaipenuh - nearest hotel: No hotel found
deniliquin - nearest hotel: No hotel found
iracoubo - nearest hotel: No hotel found
sokolo - nearest hotel: No hotel found
marsh harbour - nearest hotel: No hotel found
tutoia - nearest hotel: No hotel found
pansemal - nearest hotel: No hotel found
sheopur - nearest hotel: No hotel found
huangpu - nearest hotel: No hotel found
callaway - nearest hotel: No hotel found
hervey bay - nearest hotel: No hotel found
itarema - nearest hotel: No hotel found
cobija - nearest hotel: No hotel found
muisne - nearest hotel: No hotel found
faanui - nearest hotel: No hotel found
ambilobe - nearest hotel: No hotel found
booue - nearest hotel: No hotel found
bara - nearest hotel: No hotel found
havelock - nearest hotel: No hotel found
wanning - nearest hotel: No hotel found
ikwiriri - nearest hotel: No hotel found
mitsamiouli - nearest hotel: No hotel found
hwange - nearest hotel: No hotel found
save - nearest hotel: No hotel found
phalombe - nearest hotel: No hotel found
mongo - nearest hotel: No hotel found
progreso - nearest hotel: No hotel found
galle - nearest hotel: No hotel found
amboasary - nearest hotel: No hotel found
takoradi - nearest hotel: No hotel found
nelson bay - nearest hotel: No hotel found
viedma - nearest hotel: No hotel found
palasbari - nearest hotel: No hotel found
anderson - nearest hotel: No hotel found
ler - nearest hotel: No hotel found

        City Country      Lat       Lng  Humidity      Hotel Name
2      kapaa      US  22.0752 -159.3190        77  No hotel found
3   souillac      MU -20.5167   57.5167        78  No hotel found
8       hilo      US  19.7297 -155.0900        79  No hotel found
15    atuona      PF  -9.8000 -139.0333        71  No hotel found
19   rikitea      PF -23.1203 -134.9692        92  No hotel found

### Step 5: Add the hotel name and the country as additional information in the hover message for each city in the map.

In [10]:
#%%capture --no-display

figure_layout = {
    'width': '400px',
    'height': '300px',
    'border': '1px solid black',
    'padding': '1px',
    'margin': '0 auto 0 auto'
}
fig = gmaps.figure()
#fig = gmaps.figure(layout=figure_layout) 

# Configure the map plot
hotel_info = hotel_df.values.tolist()

locations = hotel_df[["Lat","Lng"]].astype(float)

list_of_infoboxes = [f"Lng: {hotel[3]}\nLat: {hotel[2]}\nCity: {hotel[0]}\n\
Humidity: {hotel[4]}\nHotel Name: {hotel[5]}\nCountry: {hotel[1]}" for hotel in hotel_info]

hotel_layer = gmaps.symbol_layer(
    locations, fill_color = "rgba(0, 150, 0, 0.4)",
    stroke_color = "rgba(0, 0, 150, 0.4)", scale=2,
    hover_text = list_of_infoboxes)

# Display the map
fig.add_layer(hotel_layer)

fig

Figure(layout=FigureLayout(height='420px'))